Jin's homework: explore the dataset 
Due Feb 13

In [1]:
# load the datafile and print the first few rows
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# feather is not needed, using pandas to read feather files
import os
import pandas as pd

In [2]:
# read the wos processed data
wosprocessedfile = "Data/maps2wos_duplicates.parquet"
jins_datafile = "Data/orgs.feather"

wosprocessed = pd.read_parquet(wosprocessedfile)
jins_data = pd.read_feather(jins_datafile)

display(wosprocessed.head())
display(jins_data.head())
jins_data.keys()

,grant_agency,counts,id,ids:ror,types,ancestorTypes,oa_ancestortypes,in_dimensions,sid,jin_type,comb_id
0,National Natural Science Foundation of China,2289096,4320321001,https://ror.org/01h0zpd94,government; funder,government; funder,government,True,G_326,G,4320321001
1,NATIONAL CANCER INSTITUTE,457524,4320337351,https://ror.org/040gcmg81,government; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,4320337351
2,National Science Foundation,372669,4320306076,https://ror.org/021nxhr62,funder; government,['government'],government,True,None,None,4320306076
3,NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES,362852,4320337354,https://ror.org/04q48ey07,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,4320337354
4,"NATIONAL HEART, LUNG, AND BLOOD INSTITUTE",327260,4320337338,https://ror.org/012pb6c26,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,4320337338

,Unnamed: 0,gvkey,fyear,fyr,datadate,name,cik,sic,spcindcd,spcseccd,...,sid,type,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower
0,1,1001,1980,12,1980-12-31,A and M FOOD SERVICES INC,723576,5812,420,978,...,BNA_0,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,a and m food services inc
6,7,1003,1980,12,1980-12-31,A.A. IMPORTING CO INC,730052,5712,449,976,...,BNA_6,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,a.a. importing co inc
16,17,1004,1980,5,1981-05-31,AAR CORP,1750,5080,110,925,...,BNA_16,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,aar corp
60,61,1005,1980,10,1980-10-31,A.B.A. INDUSTRIES INC,<NA>,3724,110,925,...,BNA_60,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,a.b.a. industries inc
62,63,1006,1980,6,1980-06-30,ABC INDS INC,<NA>,2711,415,976,...,BNA_62,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,abc inds inc

Index(['Unnamed: 0', 'gvkey', 'fyear', 'fyr', 'datadate', 'name', 'cik', 'sic',
       'spcindcd', 'spcseccd', 'spcsrc', 'regions', 'sid', 'type', 'isin',
       'EIN', 'LEVEL1', 'FNDNCD', 'FIPS', 'TAXPER', 'URL', 'name_lower'],
      dtype='object')

In [3]:
# merge the two dataframes by coloumn sid
merged = pd.merge(wosprocessed, jins_data, on="sid", how="left")
display(merged.head())

,grant_agency,counts,id,ids:ror,types,ancestorTypes,oa_ancestortypes,in_dimensions,sid,jin_type,...,regions,type,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower
0,National Natural Science Foundation of China,2289096,4320321001,https://ror.org/01h0zpd94,government; funder,government; funder,government,True,G_326,G,...,<NA>,government,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national science foundation
1,NATIONAL CANCER INSTITUTE,457524,4320337351,https://ror.org/040gcmg81,government; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
2,National Science Foundation,372669,4320306076,https://ror.org/021nxhr62,funder; government,['government'],government,True,None,None,...,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
3,NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES,362852,4320337354,https://ror.org/04q48ey07,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
4,"NATIONAL HEART, LUNG, AND BLOOD INSTITUTE",327260,4320337338,https://ror.org/012pb6c26,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN

In [4]:
merged.dropna(subset=["sid"])

,grant_agency,counts,id,ids:ror,types,ancestorTypes,oa_ancestortypes,in_dimensions,sid,jin_type,...,regions,type,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower
0,National Natural Science Foundation of China,2289096,4320321001,https://ror.org/01h0zpd94,government; funder,government; funder,government,True,G_326,G,...,<NA>,government,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national science foundation
12,National Institutes of Health,303973,4320332161,https://ror.org/01cwqze88,government; funder,"['government', 'funder', 'government']",government,None,G_189,G,...,<NA>,government,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national institutes of health
40,NATIONAL INSTITUTE ON AGING,136096,4320337337,https://ror.org/049v75w11,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,P_1755384,P,...,<NA>,philanthropy,<NA>,942978977,PC,15,6075,202106,<NA>,institute on aging
42,MRC,135343,4320334626,https://ror.org/03x94j517,funder; government,"['government', 'funder']",government,True,P_600528,P,...,<NA>,philanthropy,<NA>,371876713,PC,<NA>,<NA>,202012,<NA>,mrc
43,MRC,135343,4320324195,https://ror.org/01gavpb45,funder; government,funder; government,government,True,P_600528,P,...,<NA>,philanthropy,<NA>,371876713,PC,<NA>,<NA>,202012,<NA>,mrc
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3590522,GH Research,1,None,None,None,None,None,None,BNA_332279,B,...,global,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,gh research plc
3590895,Pampa Energia SA,1,None,None,None,None,None,None,BNA_511610,B,...,global,company,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,pampa energia sa
3590896,Pampa Energia SA,1,None,None,None,None,None,None,BG_25666,B,...,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
3590939,Oregon Medical Education Foundation,1,None,None,None,None,None,None,P_1741489,P,...,<NA>,philanthropy,<NA>,936022441,PC,17,41067,202112,<NA>,oregon medical education foundation
3591717,EJK Foundation,1,None,None,None,None,None,None,P_1450727,P,...,<NA>,philanthropy,<NA>,834229407,PC,<NA>,<NA>,202012,<NA>,ejk foundation

In [5]:
# create a new general id column (gid). if we have an "id" not nan, we use OA_<id>, otherwise we use sid
gids = []
for oid, sid in zip(merged["id"], merged["sid"]):
    if oid==oid and oid:
        gids.append("OA_" + str(int(oid)))
    else:
        gids.append(sid)
merged["gid"] = gids
# print the first few rows

3591884

In [16]:
merged.to_feather("Data/wos2jins_2023_duplicates.feather")

In [17]:
merged

,grant_agency,counts,id,ids:ror,types,ancestorTypes,oa_ancestortypes,in_dimensions,sid,jin_type,...,type,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower,gid
0,National Natural Science Foundation of China,2289096,4320321001,https://ror.org/01h0zpd94,government; funder,government; funder,government,True,G_326,G,...,government,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national science foundation,OA_4320321001
1,NATIONAL CANCER INSTITUTE,457524,4320337351,https://ror.org/040gcmg81,government; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320337351
2,National Science Foundation,372669,4320306076,https://ror.org/021nxhr62,funder; government,['government'],government,True,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320306076
3,NATIONAL INSTITUTE OF GENERAL MEDICAL SCIENCES,362852,4320337354,https://ror.org/04q48ey07,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320337354
4,"NATIONAL HEART, LUNG, AND BLOOD INSTITUTE",327260,4320337338,https://ror.org/012pb6c26,facility; funder,"['government', 'funder', 'government', 'funder...",government,True,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320337338
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3591879,Coordenag?o de Aperfeigoamento de Pessoal de N...,1,4210101050,https://ror.org/016e3ca54,facility,facility,None,None,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4210101050
3591880,EPF school of Engineering,1,4320337263,None,None,None,None,None,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320337263
3591881,Chemistry Department Al-Nahrain University,1,4320319196,https://ror.org/05v2p9075,education; funder,education; funder,None,None,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320319196
3591882,National Aeronautics and Space Administration ...,1,4320306101,https://ror.org/027ka1x80,funder; government,['government'],government,True,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4320306101
3591883,UTM Transdisciplinary Research Grant (TDR),1,4392738219,https://ror.org/046j7pv84,government; funder,"['government', 'funder']",government,None,None,None,...,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,OA_4392738219

In [10]:
# check the names of the columns in the merged dataframe
merged.keys()

Index(['grant_agency', 'counts', 'id', 'ids:ror', 'types', 'ancestorTypes',
       'oa_ancestortypes', 'in_dimensions', 'sid', 'jin_type', 'comb_id',
       'Unnamed: 0', 'gvkey', 'fyear', 'fyr', 'datadate', 'name', 'cik', 'sic',
       'spcindcd', 'spcseccd', 'spcsrc', 'regions', 'type', 'isin', 'EIN',
       'LEVEL1', 'FNDNCD', 'FIPS', 'TAXPER', 'URL', 'name_lower', 'gid'],
      dtype='object')

In [13]:

# read the merge-jin file 
datapath = "/mnt/helios/ail/sciencefunding/Data/maps2wos.feather"  # Update this path to the correct location of your file
# read the feather file
df = pd.read_feather(datapath)
# print the first few rows
print(df.head())

                                        grant_agency   counts          id  \
0  United States Department of Health and Human S...  2957241  1299022934
1          National Institutes of Health (NIH) - USA  2882295  4320332161
2  National Natural Science Foundation of China (...  2741499  4320321001
3       National Natural Science Foundation of China  1943759  4320321001
4                                European Commission  1277786  4320320300

                     ids:ror               types  \
0  https://ror.org/033jnv181  government; funder
1  https://ror.org/01cwqze88  government; funder
2  https://ror.org/01h0zpd94  government; funder
3  https://ror.org/01h0zpd94  government; funder
4  https://ror.org/00k4n6c32  government; funder

                            ancestorTypes   sid jin_type     comb_id
0                          ['government']  None     None  1299022934
1  ['government', 'funder', 'government']  None     None  4320332161
2                      government; funder  None     None  4320321001
3                      government; funder  None     None  4320321001
4                          ['government']  None     None  4320320300

In [49]:
df = pd.read_feather("../Results/grant_agency_matched_jin.feather")

In [53]:
df.dropna(subset=["jin_type"]).head()

,UT,grant_agency,grant_agency_normalized,counts,id,ids:ror,types,ancestorTypes,sid,jin_type,...,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower,gid,counts_total
37,WOS:000655584900001,David and Lucile Packard Foundation,David and Lucile Packard Foundation,4165.0,4320306079,https://ror.org/032atxq54,nonprofit; funder,nonprofit; funder,P_1747543,P,...,<NA>,942278431,PF,4,6085,202012,<NA>,david and lucile packard foundation,OA_4320306079,15589.0
52,WOS:000692211500016,National Science Foundation,National Science Foundation,342457.0,4320306076,https://ror.org/021nxhr62,funder; government,['government'],G_326,G,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national science foundation,OA_4320306076,1707636.0
53,WOS:000692211500016,National Institutes of Health,National Institutes of Health,283431.0,4320332161,https://ror.org/01cwqze88,government; funder,"['government', 'funder', 'government']",G_189,G,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.federalregister.gov/agencies/natio...,national institutes of health,OA_4320332161,3666140.0
66,WOS:000720744800001,Hatch,Hatch,236.0,None,None,None,None,P_442538,P,...,<NA>,300261283,PC,15,30031,202012,<NA>,hatch,P_442538,236.0
167,WOS:000632036600004,Edwards Lifesciences,Edwards Lifesciences,2045.0,4320309139,https://ror.org/04jhyte11,company; funder,company; funder,BNA_416830,B,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,edwards lifesciences corp,OA_4320309139,2859.0

In [44]:
display(merged.dropna(subset=["jintype"]).tail())

,grant_agency,counts,id,ids:ror,types,ancestorTypes,sid,jin_type,comb_id,Unnamed: 0,...,type,isin,EIN,LEVEL1,FNDNCD,FIPS,TAXPER,URL,name_lower,gid
3273420,Hamer Foundation,1,None,None,None,None,P_284541,P,P_284541,284542,...,philanthropy,<NA>,237349926,PF,4,54099,202111,<NA>,hamer foundation,P_284541
3273461,"Hamilton Company Charitable Foundation, Boston...",1,None,None,None,None,P_437715,P,P_437715,437716,...,philanthropy,<NA>,277018900,PF,4,25025,202012,<NA>,hamilton company charitable foundation,P_437715
3273510,Hanlon Foundation,1,None,None,None,None,P_1727847,P,P_1727847,1727848,...,philanthropy,<NA>,916485795,PF,4,53033,202112,<NA>,hanlon foundation,P_1727847
3273566,Hans and Eugenia Juetting Foundation,1,None,None,None,None,P_1795290,P,P_1795290,1795291,...,philanthropy,<NA>,980489121,PF,4,<NA>,201912,<NA>,hans and eugenia juetting foundation,P_1795290
3273838,Hankins Foundation,1,None,None,None,None,P_523970,P,P_523970,523971,...,philanthropy,<NA>,346565426,PF,4,39035,202012,<NA>,hankins foundation,P_523970